services:
  backend:
    build: 
      context: ./backend
      target: builder # Use builder stage because it has Air installed
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/app
    command: air -c .air.toml
    networks:
      - swiftly-network

  migrate:
    build: 
      context: ./backend
      target: builder
    env_file:
      - ./backend/.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./backend:/app
    command: go run cmd/migrate/main.go
    networks:
      - swiftly-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - swiftly-network
    volumes:
      - redis-data:/data

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000" # Port API
      - "9001:9001" # Port Web UI / Console
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    networks:
      - swiftly-network
    volumes:
      - minio-data:/data

  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio
    networks:
      - swiftly-network
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/swiftly-storage --ignore-existing;
      /usr/bin/mc anonymous set download myminio/swiftly-storage;
      exit 0;
      "

networks:
  swiftly-network:
    driver: bridge

volumes:
  redis-data:
  minio-data:
